import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'quote.freezed.dart';

// But if Person was not serializable, we could skip it.
part 'quote.g.dart';

@freezed
class Quote with _$Quote {
  const factory Quote({
    @JsonKey(name: "c")
    required double currentPrice,
    @JsonKey(name: "h")
    required double highPriceOfDay,
    @JsonKey(name: "l")
    required double lowPriceOfDay,
    @JsonKey(name: "o")
    required double openPriceOfDay,
    @JsonKey(name: "pc")
    required double previousClosePrice,
    required int t,
  }) = _Quote;

  factory Quote.fromJson(Map<String, Object?> json) => _$QuoteFromJson(json);
}
